config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  devise_for :users
  resources :users do
    member do
      post 'request_match'    => 'users#request_match'
      post 'accept_match'    => 'users#accept_match'
      put 'read_notification'    => 'users#read_notification'
      put 'stop_following'  => 'users#stop_following'
    end
  end
  resources :matches do
    collection do
      get :index_requested
    end
    resources :match_messages
    resources :warrants, controller: 'matches/warrants'
    member do
      put 'accept_match'    => 'users#accept_match'
    end
  end
  resources :times_messages do
    member do
      put 'like'    => 'times_messages#like'
      put 'unvote'  => 'times_messages#unvote'
    end
    collection do
      get 'users/:user_id' => 'times_messages#users', as: 'users'
      get 'followings' => 'times_messages#followings', as: 'followings'
      get 'images' => 'times_messages#images', as: 'images'
    end
  end
  resources :notifications
  root 'home#index'
  get 'mypages'    => 'mypages#index'
  get 'mypages/show'
  get 'mypages/payment'

  resources :charges
end

app/models/match_message.rb
class MatchMessage < ApplicationRecord
  belongs_to :user
  belongs_to :match
  belongs_to :warrant, optional: true
  has_many :notifications, as: :notifiable

  validate :user_is_in_match

  after_create :notinotinoti

  private

  def user_is_in_match
    unless match.users.include?(user)
      errors.add(:user_id, 'invalid user_id')
    end
  end

  def other_users
    return unless match.chat_room?
    match.users.where.not(id: user.id)
  end

  def notinotinoti
    other_users.each do |u|
      notifications.create(target: u)
      NotificationMailer.match_message_to_user(user, u, match).deliver
    end
  end
end

app/controllers/match_messages_controller.rb
class MatchMessagesController < ApplicationController
  before_action :set_match
  before_action :set_match_message, only: [:edit, :update, :destroy]
  before_action :check_user_membership, only: [:new, :create, :edit, :update, :destroy]

  def index
    @q = @match.match_messages.ransack(params[:q])
    @match_messages = @q.result.page(params[:page]).per(24).order(id: :asc)
    @new_message = @match.match_messages.new
  end

  def show
  end

  def new
    @match_message = @match.match_messages.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @match_message = @match.match_messages.build(match_message_params)
    @match_message.user_id = current_user.id

    respond_to do |format|
      if @match_message.save
        format.html { redirect_to @match, notice: 'match_message was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @match_message.update(match_message_params)
        format.html { redirect_to @match_message, notice: 'match_message was successfully updated.' }
        format.json { render :show, status: :ok, location: @match_message }
      else
        format.html { render :edit }
        format.json { render json: @match_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @match_message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'match_message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_match
    @match = Match.find(params[:match_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_match_message
    @match_message = @match.match_messages.find(params[:id])
  end

  def check_user_membership
    unless current_user.can_send_message_to_request_match?
      redirect_to root_path, alert: 'no permission'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def match_message_params
    params.require(:match_message).permit(:type, :content, :image, :video)
  end
end

app/views/match_messages/_form.html.haml
= form_with(model: [@match, match_message], local: true) do |form|
  - if match_message.errors.any?
    #error_explanation
      %h2
        = pluralize(match_message.errors.count, "error")
        prohibited this message from being saved:
      %ul
        - match_message.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :content
    = form.text_area :content, class: "form-control"
  .actions
    = form.submit class: "btn btn-dark"

app/views/match_messages/_messages.html.haml
- match_messages.each do |message|
  .row
    - if message.image.present? || message.video.present?
      .col-3
        = link_to message do
          %p
            = image_tag message.image.middle.url, width: '100%' if message.image.present?
          %p
            = video_tag message.video.url, width: "100%", controls: true, autobuffer: true if message.video.present?
    %div{:class => "col-#{message.image.present? || message.video.present? ? '9' : '12'} message-content"}
      = link_to message do
        = truncate(message.content, length: 100)
      asdfa
    .col-12.message-content
      %p
        = link_to user_path(message.user) do
          = image_tag message.user.image.square.url, class: "profile-img rounded" if message.user.image.present?
        asdfasdf
      %label
        = render 'match_messages/vote', message: message
        = link_to message do
          = message.created_at
      - if message.warrant.present?
        = message.warrant.price
  %hr/

app/views/match_messages/_vote.html.haml
- if message.votes_for.up.by_type(User).voters.present?
  %i.fas.fa-bolt.fa-lg{"data-target" => "#exampleModal#{message.id}", "data-toggle" => "modal", :href => "#exampleModal#{message.id}", :style => "cursor: pointer;"}
/ Modal
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :id => "exampleModal#{message.id}", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title bolt!
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        - message.votes_for.up.by_type(User).voters.each do |voter|
          = link_to user_path(voter) do
            %p
              = image_tag voter.image.square.url, class: 'rounded-circle', width: '50px' if voter.image.present?
              = voter.name
      .modal-footer

app/views/match_messages/edit.html.haml
%h1 Editing message
= render 'form', match_message: @match_message
= link_to 'Show', @message
|
= link_to 'Back', match_match_messages_path(@match)

app/views/match_messages/images.html.haml
- @has_image_messages.each do |message|
  = link_to match_message_path(message) do
    = image_tag message.image.square.url, width: '32%' if message.image.present?

app/views/match_messages/index.html.haml
%hr/
= render 'messages', match_messages: @match_messages

app/views/match_messages/new.html.haml
%h1 New message
= render 'form', match_message: @match_message
= link_to 'Back', match_match_messages_path(@match)

app/views/match_messages/show.html.haml
%p#notice= notice
%p
  = md_to_html(@match_message.content)
%p
  = image_tag @match_message.image.url, width: '100%' if @match_message.image.present?
%p
  = video_tag @match_message.video.url, width: "100%", controls: true, autobuffer: true if @match_message.video.present?
%p
  = link_to user_path(@match_message.user) do
    = image_tag @match_message.user.image.square.url, class: 'rounded-circle', width: '50px' if @match_message.user.image.present?
  = @match_message.created_at
= render 'vote', message: @match_message
%hr/
%p
  - if user_signed_in?
    = link_to 'bolt!', like_match_message_path(@match_message), method: :put
    = link_to 'unvote', unvote_match_message_path(@match_message), method: :put
    - if current_user?(@match_message.user)
      = link_to 'Edit', edit_match_message_path(@match_message)
      = link_to 'Destroy', @match_message, method: :delete, data: { confirm: 'Are you sure?' }
  = link_to 'Back', match_match_messages_path(@match)

app/views/match_messages/users.html.haml
%hr/
- if user_signed_in?
  = render 'form', message: @new_message
= render 'messages', messages: @messages