config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  devise_for :users
  resources :users do
    member do
      post 'request_match'    => 'users#request_match'
      post 'accept_match'    => 'users#accept_match'
      put 'read_notification'    => 'users#read_notification'
      put 'stop_following'  => 'users#stop_following'
    end
  end
  resources :matches do
    collection do
      get :index_requested
    end
    resources :match_messages
    resources :warrants, controller: 'matches/warrants'
    member do
      put 'accept_match'    => 'users#accept_match'
    end
  end
  resources :times_messages do
    member do
      put 'like'    => 'times_messages#like'
      put 'unvote'  => 'times_messages#unvote'
    end
    collection do
      get 'users/:user_id' => 'times_messages#users', as: 'users'
      get 'followings' => 'times_messages#followings', as: 'followings'
      get 'images' => 'times_messages#images', as: 'images'
    end
  end
  resources :notifications
  root 'home#index'
  get 'mypages'    => 'mypages#index'
  get 'mypages/show'
  get 'mypages/payment'

  resources :charges
end

app/models/notification.rb
class Notification < ApplicationRecord
  include PublicActivity::Model

  belongs_to :notifiable, polymorphic: true
  belongs_to :target, polymorphic: true

  after_create :notify_to_user

  tracked

  scope :unread, ->() { where(read: false) }

  def notify_to_user
    
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy, :publish]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.order(id: :desc)
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    transaction do
      @notification.update(published_at: Time.zone.now)
      User.all.each do |user|
        user.notifications.create(notificatable_type: 'Notification', notificatable_id: @notification.id)
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notification
    @notification = Notification.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def notification_params
    params.require(:notification).permit(:title, :body, :draft, :published_at)
  end
end

app/views/notifications/_form.html.haml
= form_for @announcement do |f|
  - if @announcement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@announcement.errors.count, "error")} prohibited this announcement from being saved:"
      %ul
        - @announcement.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :kind
    = f.number_field :kind
  .field
    = f.label :draft
    = f.check_box :draft
  .field
    = f.label :published_at
    = f.datetime_select :published_at
  .actions
    = f.submit 'Save'

app/views/notifications/edit.html.haml
%h1 Editing announcement

= render 'form'

= link_to 'Show', @announcement
\|
= link_to 'Back', announcements_path

app/views/notifications/index.html.haml
%h1 Listing notifications

%table
  %thead
    %tr
      %th Published at
      %th Published at
      %th Published at
      %th
      %th
      %th

  %tbody
    - @notifications.each do |notification|
      %tr
        %td= notification.created_at
        %td= notification.notifiable.model_name
        %td= notification.target.model_name
        %td= link_to 'Show', notification
        %td= link_to 'Edit', edit_notification_path(notification)
        %td= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Announcement', new_notification_path

app/views/notifications/new.html.haml
%h1 New announcement

= render 'form'

= link_to 'Back', announcements_path

app/views/notifications/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @announcement.title
%p
  %b Body:
  = @announcement.body
%p
  %b Kind:
  = @announcement.kind
%p
  %b Draft:
  = @announcement.draft
%p
  %b Published at:
  = @announcement.published_at

= link_to 'Edit', edit_announcement_path(@announcement)
\|
= link_to 'Back', announcements_path