config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  devise_for :users
  resources :users do
    member do
      post 'request_match'    => 'users#request_match'
      post 'accept_match'    => 'users#accept_match'
      put 'read_notification'    => 'users#read_notification'
      put 'stop_following'  => 'users#stop_following'
    end
  end
  resources :matches do
    collection do
      get :index_requested
    end
    resources :match_messages
    resources :warrants, controller: 'matches/warrants'
    member do
      put 'accept_match'    => 'users#accept_match'
    end
  end
  resources :times_messages do
    member do
      put 'like'    => 'times_messages#like'
      put 'unvote'  => 'times_messages#unvote'
    end
    collection do
      get 'users/:user_id' => 'times_messages#users', as: 'users'
      get 'followings' => 'times_messages#followings', as: 'followings'
      get 'images' => 'times_messages#images', as: 'images'
    end
  end
  resources :notifications
  root 'home#index'
  get 'mypages'    => 'mypages#index'
  get 'mypages/show'
  get 'mypages/payment'

  resources :charges
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :user_matches
  has_many :users, through: :user_matches
  has_many :notifications, as: :notifiable
  has_many :match_messages

  enum match_type: { chat_room: 1, warrant: 2, box: 3 }
  enum match_status: { pending: 0, joynted: 1, block: 10 }

  def has_message_notification?(user)
    match_messages.joins(:notifications).where(notifications: { target: user, read: false }).present?
  end
end

app/controllers/matches/warrants_controller.rb
class Matches::WarrantsController < ApplicationController
  before_action :set_match
  before_action :set_warrant, only: [:show, :edit, :update, :destroy]

  # GET /warrants
  # GET /warrants.json
  def index
    @warrants = current_user.buyer_warrants.where(issuer_user: @match_user)
  end

  def index_benefit
    @warrants = Warrant.where(issuer_user: @match_user, owner_user: current_user)
  end

  # GET /warrants/1
  # GET /warrants/1.json
  def show
  end

  # GET /warrants/new
  def new
    @warrant = current_user.buyer_warrants.new(issuer_user: current_user.direct_match_user(@match))
  end

  # GET /warrants/1/edit
  def edit
  end

  def propose
    raise '' unless @warrant.owner_user == current_user
    @warrant.update(status: :proposed)
    NotificationMailer.match_message_create(current_user, @match_user).deliver
  end

  def accept_proposal
    raise '' unless @warrant.issuer_user == current_user
    @warrant.update(status: :issued)
    NotificationMailer.match_message_create(current_user, @match_user).deliver
  end

  def calcel_proposal
    raise '' unless @warrant.issuer_user == current_user || @warrant.owner_user == current_user
    @warrant.update(status: :proposed)
    NotificationMailer.match_message_create(current_user, @match_user).deliver
  end

  def exercise
    raise '' unless @warrant.issuer_user == current_user
    @warrant.update(status: :exercised)
    NotificationMailer.match_message_create(current_user, @match_user).deliver
  end

  # POST /warrants
  # POST /warrants.json
  def create
    @warrant = current_user.buyer_warrants.new(issuer_user: current_user.direct_match_user(@match))
    @warrant.assign_attributes(warrant_params)

    respond_to do |format|
      if @warrant.save
        binding.pry
        current_user.match_messages.create(match: @match, content: 'warrant作成', warrant: @warrant)
        NotificationMailer.match_message_create(current_user, @match_user).deliver
        format.html { redirect_to [@match, @warrant], notice: 'Warrant was successfully created.' }
        format.json { render :show, status: :created, location: [@match, @warrant] }
      else
        format.html { render :new }
        format.json { render json: @warrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warrants/1
  # PATCH/PUT /warrants/1.json
  def update
    respond_to do |format|
      if @warrant.update(warrant_params)
        format.html { redirect_to [@match, @warrant], notice: 'Warrant was successfully updated.' }
        format.json { render :show, status: :ok, location: [@match, @warrant] }
      else
        format.html { render :edit }
        format.json { render json: @warrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warrants/1
  # DELETE /warrants/1.json
  def destroy
    @warrant.destroy
    respond_to do |format|
      format.html { redirect_to match_warrants_url, notice: 'Warrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.find(params[:match_id])
    @match_user = current_user.direct_match_user @match
  end

  def set_warrant
    @warrant = Warrant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def warrant_params
    params.require(:warrant).permit(:status, :price_per_hour, :owner_user_id, :issuer_user_id, :start_datetime, :end_datetime, :price)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_match, only: [:show, :accept_match]

  def index
    @q = current_user.matches.ransack(params[:q])
    @matches = @q.result.page(params[:page]).per(24).order(id: :desc)
  end

  def index_requested
    @q = current_user.matches.ransack(params[:q])
    @matches = @q.result.where(connected: false)
    render :index
  end

  def show
    if @match.notifications.unread.find_by(target: current_user).present?
      @match.notifications.unread.find_by(target: current_user).update(read: true)
    end
    @match_messages = @match.match_messages.order(id: :desc)
  end

  def accept_match
    raise 'asefasfa' unless @match.user_matches.pluck(:id).include? params[:request_user_id]
    @match.update(connected: true)
    NotificationMailer.match_message_create(current_user, @user).deliver
  end

  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def block
  end

  private

  def set_match
    @match = Match.joins(:user_matches).where(user_matches: { user: current_user }).find(params[:id])
  end
end

app/views/matches/_form.html.haml
= form_with(model: times_message, local: true) do |form|
  - if times_message.errors.any?
    #error_explanation
      %h2
        = pluralize(times_message.errors.count, "error")
        prohibited this message from being saved:
      %ul
        - times_message.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :content
    = form.text_area :content, class: "form-control"
  .form-group
    = form.label :image
    = image_tag times_message.image.url, width: "300px" if times_message.image?
    = form.file_field :image, class: "form-control"
  .form-group
    = form.label :video
    = video_tag times_message.video.url, width: "50%", controls: true, autobuffer: true if times_message.video.present?
    = form.file_field :video, class: "form-control"
  .actions
    = form.submit class: "btn btn-dark"

app/views/matches/_messages.html.haml
- times_messages.each do |message|
  .row
    - if message.image.present? || message.video.present?
      .col-3
        = link_to message do
          %p
            = image_tag message.image.middle.url, width: '100%' if message.image.present?
          %p
            = video_tag message.video.url, width: "100%", controls: true, autobuffer: true if message.video.present?
    %div{:class => "col-#{message.image.present? || message.video.present? ? '9' : '12'} message-content"}
      = link_to message do
        = truncate(message.content, length: 100)
    .col-12.message-content
      %p
        = link_to user_path(message.user) do
          = image_tag message.user.image.square.url, class: "profile-img rounded" if message.user.image.present?
      %label
        = render 'times_messages/vote', message: message
        = link_to message do
          = message.created_at
  %hr/

app/views/matches/_vote.html.haml
- if message.votes_for.up.by_type(User).voters.present?
  %i.fas.fa-bolt.fa-lg{"data-target" => "#exampleModal#{message.id}", "data-toggle" => "modal", :href => "#exampleModal#{message.id}", :style => "cursor: pointer;"}
/ Modal
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :id => "exampleModal#{message.id}", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title bolt!
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        - message.votes_for.up.by_type(User).voters.each do |voter|
          = link_to user_path(voter) do
            %p
              = image_tag voter.image.square.url, class: 'rounded-circle', width: '50px' if voter.image.present?
              = voter.name
      .modal-footer

app/views/matches/edit.html.haml
%h1 Editing message
= render 'form', message: @message
= link_to 'Show', @message
|
= link_to 'Back', messages_path

app/views/matches/followings.html.haml
%hr/
= render 'messages', messages: @messages

app/views/matches/images.html.haml
- @has_image_messages.each do |message|
  = link_to times_message_path(message) do
    = image_tag message.image.square.url, width: '32%' if message.image.present?

app/views/matches/index.html.haml
%h1 Direct Messages
%hr/
- @matches.each do |match|
  = link_to match_path(match) do
    = current_user.direct_match_user(match).name
    - if current_user.direct_match_user(match).request_matches? current_user
      = form_with(url: accept_match_user_path(current_user.direct_match_user(match), match_id: match.id), local: true) do |form|
        .actions
          = form.submit class: "btn btn-dark"

      = link_to accept_match_user_path(current_user.direct_match_user(match), match_id: match.id), method: :put do
        %i.far.fa-plus-square accept_match
    - if match.has_message_notification?(current_user)
      = link_to match_path(match) do
        %i.fas.fa-fire
        new message
    - if match.notifications.unread.where(target: current_user).present?
      NEW MATCH!
  %hr/

app/views/matches/new.html.haml
%h1 New message
= render 'form', times_message: @times_message
= link_to 'Back', times_messages_path

app/views/matches/show.html.haml
= link_to 'new', new_match_match_message_path(match_id: @match.id)
= link_to 'new warrant', new_match_warrant_path(match_id: @match.id) if @match.warrant?
- @match_messages.each do |message|
  .row
    - if message.image.present? || message.video.present?
      .col-3
        = link_to message do
          %p
            = image_tag message.image.middle.url, width: '100%' if message.image.present?
          %p
            = video_tag message.video.url, width: "100%", controls: true, autobuffer: true if message.video.present?
    %div{:class => "col-#{message.image.present? || message.video.present? ? '9' : '12'} message-content"}
      = truncate(message.content, length: 100)
    .col-12.message-content
      %p
        - if message.warrant.present?
          = message.warrant.price
          = message.warrant.start_datetime
          = message.warrant.end_datetime
        = link_to user_path(message.user) do
          = image_tag message.user.image.square.url, class: "profile-img rounded" if message.user.image.present?
  %hr/
%i.fas.fa-bolt.fa-lg{"data-target" => "#exampleModal1", "data-toggle" => "modal", :href => "#exampleModal1", :style => "cursor: pointer;"}
/ Modal
#exampleModal1.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title bolt!
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        %p あなたからリクエストしたマッチへのメッセージ送信は、有料会員登録が必要になります。
        %p リクエストされたマッチへのメッセージ送信は、無料会員でも利用が可能です。
        %p アテンディーは無料会員、メンバーは3,000円の有料会員でマッチング利用、エンジェルは8,000円の有料会員でワラントの発行が可能、シードはワラントの権利行使が可能
        %p 3,000/月で、メッセージは送り放題
        %p 8,000/月で、エンジェル会員、ワラント6,000円分が付与されます。（未利用は繰越）
        %p ワラントは、シード会員に対して有効です。マッチングして実際に会う事に対する予約券で、面会成立を持って権利行使となります。
        %p シード会員はワラントの権利行使を通じて報酬を得る事が可能なユーザーであり、運営会社の審査を経た上でシード会員となる事が可能です。
        %p シード会員はワラントの権利行使でのマッチングも可能だが、アテンディーやメンバーとの非ワラントでのマッチングも可能？です。
      .modal-footer

app/views/matches/users.html.haml
%hr/
- if user_signed_in?
  = render 'form', message: @new_message
= render 'messages', messages: @messages